version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      REACT_APP_BACKEND_URL: http://localhost:8001
    depends_on:
      - backend
    networks:
      - lotaya-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      MONGO_URL: mongodb://mongodb:27017
      DB_NAME: lotaya_ai
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - lotaya-network

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: lotaya_ai
    volumes:
      - mongodb_data:/data/db
    networks:
      - lotaya-network

volumes:
  mongodb_data:

networks:
  lotaya-network:
    driver: bridge